name: plb
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.21.1
  - pip:
    - joblib
    - gym==0.14.0
    - moviepy
    - opencv-python
    - matplotlib
    - transforms3d
    - python-dateutil
    - cloudpickle
    - pyyaml
    - yacs
    - scikit-learn
    - scipy
    - taichi==0.7.26
    - pyquaternion
    - transformations
    - natsort
    - wandb
