name: plb
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - numpy
  - pip
  - pip:
    - joblib
    - gym==0.14.0
    - moviepy
    - opencv-python
    - matplotlib
    - transforms3d
    - python-dateutil
    - cloudpickle
    - pyyaml
    - yacs
    - scikit-learn
    - scipy
    - taichi==0.7.26
    - pyquaternion
    - transformations
    - natsort
    - wandb
    - torch_geometric
    - pytorch3d
    - pillow==8.4.0
    - imageio==2.15.0
    - torchdiffeq
    - open3d
